// Method-name → IPC-channel maps mirroring electron/preload/index.ts. Each
// table drives a generic transport call (see bridge-shim.ts). Methods whose
// preload definition reshapes arguments, returns synchronously, or uses a
// dynamic channel are handled as specials in bridge-shim.ts (NOT here).

/** ipcRenderer.invoke → inv(channel, ...args) (returns Promise). */
export const INVOKE: Record<string, string> = {
  getToolUsageEntries: "toolusage:entries",
  createTab: "tab:create",
  listTabs: "tab:list",
  getActiveTab: "tab:get-active",
  saveTabsState: "tabs:save-state",
  restoreTabsState: "tabs:restore-state",
  refreshPluginSource: "plugins:refresh-plugin-source",
  retryPluginSource: "plugins:retry-plugin-source",
  listLogs: "logs:list",
  clearLogs: "logs:clear",
  getConnectionState: "get-connection-state",
  downloadJsonl: "jsonl:download",
  downloadAllJsonl: "jsonl:download-all",
  saveSessionDiag: "diag:save",
  getConfig: "get-config",
  getBasePrompt: "base-prompt:get",
  setBasePrompt: "base-prompt:set",
  forceSync: "sync:force",
  getMachineId: "get-machine-id",
  applyUpdate: "update:apply",
  quitAndInstallUpdate: "update:quit-and-install",
  getLayout: "layout:get",
  getNotifications: "notifications:get",
  getTerminalPrefs: "terminal:get-prefs",
  setTerminalPrefs: "terminal:set-prefs",
  testNotification: "notifications:test",
  whisperTranscribe: "whisper:transcribe",
  checkMicAccess: "mic:check-access",
  nativeMicStart: "native-mic:start",
  nativeMicStop: "native-mic:stop",
  getCwd: "get-cwd",
  selectFolder: "select-folder",
  saveClipboardImage: "save-clipboard-image",
  // Не-image drop/paste: байты File → temp-файл с исходным именем → путь
  // (замена мёртвого getDroppedFilePath Electron-эпохи, аудит #70 A3).
  saveDroppedFile: "save-dropped-file",
  readFileAsBase64: "fs:read-base64",
  hooksList: "hooks:list",
  hooksListAll: "hooks:list-all",
  hooksGetLibrary: "hooks:get-library",
  hooksClearLog: "hooks:clear-log",
  hooksActive: "hooks:active",
  hooksInstallTemplate: "hooks:install-template",
  hooksDelete: "hooks:delete",
  hooksSave: "hooks:save",
  hooksTest: "hooks:test",
  hooksGetPluginApproval: "hooks:get-plugin-approval",
  hooksSetPluginApproval: "hooks:set-plugin-approval",
  openImageDialog: "open-image-dialog",
  openFileDialog: "open-file-dialog",
  openExternal: "open-external",
  micStart: "mic-start",
  micStop: "mic-stop",
  micConnected: "mic-connected",
  micLaunchChrome: "mic-launch-chrome",
  micToggleVisible: "mic-toggle-visible",
  resumeSession: "session:resume",
  getSavedSessions: "session:get-saved",
  removeSavedSession: "session:remove-saved",
  deleteSessionData: "session:delete-data",
  getTabModel: "get-tab-model",
  getMcpServers: "mcp:get-servers",
  addMcpServer: "mcp:add-server",
  updateMcpServer: "mcp:update-server",
  removeMcpServer: "mcp:remove-server",
  toggleMcpServer: "mcp:toggle-server",
  testMcpServer: "mcp:test-server",
  getMcpTestLog: "mcp:get-test-log",
  clearMcpTestLog: "mcp:clear-test-log",
  oauthConnectMcpServer: "mcp:oauth-connect",
  oauthDisconnectMcpServer: "mcp:oauth-disconnect",
  oauthMcpStatus: "mcp:oauth-status",
  getMcpResources: "mcp:get-resources",
  readMcpResource: "mcp:read-resource",
  getMcpPrompts: "mcp:get-prompts",
  getMcpPrompt: "mcp:get-prompt",
  listMcpRegistry: "mcp:registry-list",
  getMcpStatus: "mcp:status",
  listSkills: "skills:list",
  listAgents: "agents:list",
  listOutputStyles: "output-styles:list",
  createSkill: "skills:create",
  deleteSkill: "skills:delete",
  openSkill: "skills:open",
  readSkill: "skills:read",
  showSkillInFolder: "skills:show-in-folder",
  sendTeamMessage: "send-team-message",
  listInstalledPlugins: "plugins:list-installed",
  getPluginContents: "plugins:get-contents",
  syncPluginCache: "plugins:sync-cache",
  getPluginSourcePath: "plugins:get-source-path",
  listMarketplaces: "plugins:list-marketplaces",
  browseMarketplace: "plugins:browse-marketplace",
  browseNestedMarketplace: "plugins:browse-nested-marketplace",
  installPlugin: "plugins:install",
  installLocalPlugin: "plugins:install-local",
  uninstallPlugin: "plugins:uninstall",
  addMarketplace: "plugins:add-marketplace",
  setMarketplaceAuth: "plugins:set-marketplace-auth",
  removeMarketplace: "plugins:remove-marketplace",
  updateMarketplace: "plugins:update-marketplace",
  getPluginOptionsSchema: "plugins:get-options-schema",
  savePluginOptions: "plugins:save-options",
  listMonitors: "monitors:list",
  getMonitorLog: "monitors:get-log",
  listLspServers: "lsp:list",
  restartLspServers: "lsp:restart",
  refreshAllMarketplaces: "plugins:refresh-all-marketplaces",
  setMarketplaceAutoUpdate: "plugins:set-marketplace-autoupdate",
  isVscodeAvailable: "vscode:is-available",
  pathExists: "fs:path-exists",
  shellsList: "shells:list",
  ptySpawn: "pty:spawn",
  fileViewerRead: "file-viewer:read",
  fileViewerReadBinary: "file-viewer:read-binary",
  fileViewerWrite: "file-viewer:write",
  fileTreeListDir: "file-tree:list-dir",
  fileTreeRename: "file-tree:rename",
  // VSIX-only: HTTP to the Bridge server runs in the ext-host (webview CSP
  // blocks direct fetch). createToken(httpBase, name) / serverVersion(httpBase).
  createToken: "bridge:create-token",
  serverVersion: "bridge:server-version",
  serverFetch: "bridge:server-fetch",
  // Clipboard via host (sandboxed webview can't use navigator.clipboard).
  writeClipboard: "write-clipboard",
  readClipboard: "read-clipboard",
  // Pull the current host-editor file+selection on mount (the live updates come
  // via the `editor-selection` EVENT; this seeds before the first change fires).
  getEditorSelection: "get-editor-selection",
}

/** ipcRenderer.send → snd(channel, ...args) (fire-and-forget). */
export const SEND: Record<string, string> = {
  // Route notifications to KaminIDE's SHARED notification UI (host-side).
  showNotification: "show-notification",
  // Панель Tools → чат: раскрыть применения тула фуллскрином.
  openToolUsage: "toolusage:open",
  closeTab: "tab:close",
  disconnectTab: "tab:disconnect",
  reconnectTab: "tab:reconnect",
  switchTab: "tab:switch",
  connect: "connect",
  disconnect: "disconnect",
  sendInput: "pty-input",
  interruptSession: "session:interrupt",
  submitText: "pty-submit-text",
  resize: "pty-resize",
  respondPermission: "permission-response",
  requestJsonlReplay: "jsonl:request-replay",
  loadOlderPage: "jsonl:load-older",
  // Full compact-boundary index (all segments, incl. out-of-window) + on-demand
  // load of one archived segment by byte range. Mirror-backed, like loadOlderPage.
  requestBoundaries: "jsonl:boundaries",
  loadSegment: "jsonl:load-segment",
  // What the chat is ACTUALLY showing. The host repaints its session list and
  // titlebar the instant a session is clicked, while the iframe still holds the
  // previous transcript until its replay lands — and nothing told the host that,
  // so the split was invisible to every host surface and unrepairable.
  reportBoundTab: "chat:bound",
  setConfig: "set-config",
  setLayout: "layout:set",
  setNotifications: "notifications:set",
  setTheme: "theme:set",
  respondElicitation: "elicitation-response",
  respondAskUser: "ask-user-response",
  requestTreeUpdate: "tree:request",
  changePermissionMode: "change-permission-mode",
  changeEffort: "change-effort",
  changeModel: "change-model",
  openFolder: "open-folder",
  revealInExplorer: "reveal-in-explorer",
  windowMinimize: "window:minimize",
  windowMaximize: "window:maximize",
  windowClose: "window:close",
  windowToggleDevTools: "window:devtools",
  fileViewerWatch: "file-viewer:watch",
  fileViewerUnwatch: "file-viewer:unwatch",
  fileTreeWatch: "file-tree:watch",
  fileTreeUnwatch: "file-tree:unwatch",
  // VSIX-only: sidebar asks the extension to reveal the center chat panel.
  openChat: "bridge:open-chat",
  // VSIX-only: chat header asks the CLI to regenerate this session's AI title.
  regenerateTitle: "bridge:regenerate-title",
}

/** ipcRenderer.on → sub(channel, cb). Args after the IPC event are delivered
 *  positionally to the callback (matches preload's `(_e, ...a) => cb(...a)`). */
export const EVENT: Record<string, string> = {
  onTabCreated: "tab:created",
  onTabClosed: "tab:closed",
  onTabSwitched: "tab:switched",
  onTabListChanged: "tab:list-changed",
  onLogEntry: "logs:entry",
  onConnectionStateChange: "connection-state-changed",
  onOutput: "pty-output",
  onExit: "pty-exit",
  onPermissionRequest: "permission-request",
  onMcpActivity: "mcp-activity",
  onJsonlEntries: "jsonl-entries",
  onOlderPage: "jsonl:older-page",
  onBoundaries: "jsonl:boundaries-result",
  onSegmentPage: "jsonl:segment-page",
  onJsonlStatus: "jsonl-status",
  onJsonlDownloadProgress: "jsonl:download-progress",
  onJsonlDownloadAllProgress: "jsonl:download-all-progress",
  onJsonlSubagentEntries: "jsonl-subagent-entries",
  onStreamingEntry: "streaming-entry",
  onStreamingDelta: "streaming-delta",
  onStreamingStatus: "streaming-status",
  onUpdateState: "update:state",
  onToastRoute: "toast:route",
  onToolUsageOpen: "toolusage-open",
  onMicAudio: "mic-audio",
  onMicLevels: "mic-levels",
  onCwdChanged: "cwd-changed",
  onConfigReady: "config-ready",
  onElicitationRequest: "elicitation-request",
  onAskUserQuestion: "ask-user-question",
  onTreeUpdate: "tree-update",
  onAgentSpawned: "agent-spawned",
  onMcpLoading: "mcp:loading",
  onMcpReady: "mcp:ready",
  onSessionTitle: "session:title",
  onSessionRestarted: "session-restarted",
  onConsoleReset: "bridge:console-reset",
  onMcpTestLog: "mcp:test-log",
  onMcpTestLogCleared: "mcp:test-log-cleared",
  onMcpElicitation: "mcp-elicitation-request",
  onMcpProgress: "mcp-progress",
  onMcpServersChanged: "mcp-servers-changed",
  onSavedSessionsChanged: "saved-sessions:changed",
  onPluginHooksAwaitingApproval: "plugin-hooks:awaiting-approval",
  onPluginsBrowseProgress: "plugins:browse-progress",
  onMarketplaceUpdated: "marketplaces:updated",
  onMonitorOutput: "monitor:output",
  onMonitorStarted: "monitor:started",
  onMonitorStopped: "monitor:stopped",
  onMonitorStatus: "monitor:status",
  onSessionActivity: "session:activity",
  onWindowMaximized: "window:maximized",
  onPtyData: "pty:data",
  onPtyExit: "pty:exit",
  onFileViewerExternalChange: "file-viewer:external-change",
  onFileTreeChange: "file-tree:change",
  // KaminIDE host Monaco editor's active file + selection (for the composer's
  // "attach file" toggle). Pushed by the extension's editor-context observer.
  onEditorSelection: "editor-selection",
}
