#!/bin/bash
# =============================================================================
# Build script for Open Claude Bridge
# =============================================================================
# Usage:
#   ./build.sh                    # Build bridge image
#   ./build.sh bridge             # Build bridge image (explicit)
#   ./build.sh --no-cache         # Build without cache
# =============================================================================

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

NO_CACHE=""
SKIP_INSTALLER=""

for arg in "$@"; do
  case "$arg" in
    --no-cache) NO_CACHE="--no-cache" ;;
    --skip-installer) SKIP_INSTALLER=1 ;;
    bridge) ;; # default target, accept silently
    *) echo "Unknown argument: $arg"; echo "Usage: $0 [bridge] [--no-cache] [--skip-installer]"; exit 1 ;;
  esac
done

# Ensure the dashboard build + Squirrel installer match the current version
# of the server. Skipping this step is a recurring footgun — the server bumps
# to N.M.K, the image gets rebuilt, but `installer/` still serves the old
# nupkg, and the in-app autoupdater fails with "Update failed — retry N.M.K".
# Pass --skip-installer when you've already produced the installer artifacts.
if [ -z "$SKIP_INSTALLER" ]; then
  ROOT_VERSION=$(node -p "require('./package.json').version")
  ELECTRON_VERSION=$(node -p "require('./electron/package.json').version")
  if [ "$ROOT_VERSION" != "$ELECTRON_VERSION" ]; then
    echo "==> ERROR: package.json ($ROOT_VERSION) and electron/package.json ($ELECTRON_VERSION) versions differ"
    echo "==> Bump both before invoking build.sh, or pass --skip-installer to bypass."
    exit 1
  fi
  EXISTING_NUPKG=$(ls -1 installer/open_claude_bridge_electron-${ROOT_VERSION}-full.nupkg 2>/dev/null || true)
  if [ -z "$EXISTING_NUPKG" ]; then
    echo "==> Building dashboard (vite)..."
    npm run build > /dev/null
    echo "==> Packaging Electron app v${ROOT_VERSION}..."
    (cd electron && npm run package > /dev/null)
    echo "==> Making Squirrel installer..."
    (cd electron && npm run make > /dev/null)
    echo "==> Copying installer artifacts to installer/..."
    rm -f installer/RELEASES installer/*Setup.exe installer/*.nupkg
    cp "electron/out/make/squirrel.windows/x64/OpenClaudeBridge-${ROOT_VERSION} Setup.exe" \
       "electron/out/make/squirrel.windows/x64/RELEASES" \
       "electron/out/make/squirrel.windows/x64/open_claude_bridge_electron-${ROOT_VERSION}-full.nupkg" \
       installer/
  else
    echo "==> Installer for v${ROOT_VERSION} already in installer/ — reusing"
  fi
fi

# Prune installer/ to keep only the latest Setup.exe + nupkg (RELEASES is
# regenerated by `npm run make` and always points at the latest). Older
# artifacts otherwise pile up at ~225MB each and bloat the image.
if [ -d installer ] && [ -f installer/RELEASES ]; then
  KEEP_VERSION=$(grep -oE '[0-9]+\.[0-9]+\.[0-9]+' installer/RELEASES | tail -1)
  if [ -n "$KEEP_VERSION" ]; then
    echo "==> Pruning installer/ — keeping only ${KEEP_VERSION}"
    find installer -maxdepth 1 -type f \
      \( -name "*.nupkg" -o -name "*Setup.exe" \) \
      ! -name "*${KEEP_VERSION}*" -print -delete
  fi
fi

# Prune KaminIDE installers — keep ONLY the highest version's setup.exe + .sig.
# The Dockerfile bakes installer/KaminIDE_*_x64-setup.exe* by GLOB, and the Tauri
# updater / /download only ever serve the newest build, so every older version is
# dead weight: each setup.exe is ~36MB and already LZMA-compressed, so it lands in
# the image layer ~1:1 (docker can't re-compress it). Left unpruned they pile up
# — this is exactly what took the pushed image from 242MB (1 installer) to 312MB
# (3) and would push it past 348MB (4). Keep one; drop the rest, every build.
LATEST_KAMIN=$(ls -1 installer/KaminIDE_*_x64-setup.exe 2>/dev/null | sort -V | tail -1)
if [ -n "$LATEST_KAMIN" ]; then
  KAMIN_VER=$(echo "$LATEST_KAMIN" | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' | tail -1)
  echo "==> Pruning KaminIDE installers — keeping only ${KAMIN_VER}"
  find installer -maxdepth 1 -type f -name "KaminIDE_*_x64-setup.exe*" \
    ! -name "*${KAMIN_VER}*" -print -delete
fi

echo "==> Building bridge image..."
podman build $NO_CACHE --build-arg CLAUDE_CODE_CACHE_BUST="$(date +%s)" -f Dockerfile -t opencode-claude-max-proxy_bridge:latest .
echo "==> Bridge image built successfully"

echo ""
echo "Done! Now restart containers:"
echo "  podman compose down"
echo "  podman compose up -d"
