//! Соответствие расширений языкам (для icon-тем).
//!
//! Перенесено без изменения поведения (`plan/100-refactor-250.md`).

/// Расширение → language id: последний слой резолва файла
/// (`language-ids.ts`, вендор terax-ai). Для встроенного Catppuccin слой
/// ничего не меняет (все эти расширения покрыты `fileExtensions`), но
/// contributed-тема может задавать иконки ТОЛЬКО через `languageIds`.
pub(crate) const EXT_TO_LANGUAGE_ID: &[(&str, &str)] = &[
    ("ts", "typescript"),
    ("cts", "typescript"),
    ("mts", "typescript"),
    ("tsx", "typescriptreact"),
    ("js", "javascript"),
    ("cjs", "javascript"),
    ("mjs", "javascript"),
    ("jsx", "javascriptreact"),
    ("html", "html"),
    ("htm", "html"),
    ("css", "css"),
    ("scss", "scss"),
    ("sass", "sass"),
    ("less", "less"),
    ("json", "json"),
    ("jsonc", "jsonc"),
    ("md", "markdown"),
    ("markdown", "markdown"),
    ("py", "python"),
    ("rs", "rust"),
    ("go", "go"),
    ("java", "java"),
    ("kt", "kotlin"),
    ("kts", "kotlin"),
    ("rb", "ruby"),
    ("php", "php"),
    ("c", "c"),
    ("h", "c"),
    ("cpp", "cpp"),
    ("cc", "cpp"),
    ("cxx", "cpp"),
    ("hpp", "cpp"),
    ("cs", "csharp"),
    ("swift", "swift"),
    ("sh", "shellscript"),
    ("bash", "shellscript"),
    ("zsh", "shellscript"),
    ("fish", "shellscript"),
    ("sql", "sql"),
    ("xml", "xml"),
    ("yaml", "yaml"),
    ("yml", "yaml"),
    ("toml", "toml"),
    ("vue", "vue"),
    ("svelte", "svelte"),
    ("astro", "astro"),
    ("lua", "lua"),
    ("dart", "dart"),
    ("r", "r"),
    ("pl", "perl"),
    ("ex", "elixir"),
    ("exs", "elixir"),
    ("elm", "elm"),
    ("hs", "haskell"),
    ("clj", "clojure"),
    ("scala", "scala"),
    ("zig", "zig"),
    ("nim", "nim"),
    ("log", "log"),
];
