// Helpers for resuming + deleting Claude CLI sessions by their
// conversationId / settingsDir slug. Extracted from session-core.ts
// (Sprint 5 / Stage E1) — these are the FS-level reverse-engineering bits
// that bridge the gap between the JSONL projects/ slug and our own
// SESSIONS_BASE token-dir layout.

import fs from 'fs'
import path from 'path'
import os from 'os'
import { debugLog, warnLog } from '../logging'
import { SESSIONS_BASE } from './session-settings'

/** Cross-platform basename: handles both / and \ separators (server may
 *  run on Linux with Windows paths inside JSONL). */
export function xbasename(p: string): string {
  const parts = p.split(/[/\\]/).filter(Boolean)
  return parts.length > 0 ? parts[parts.length - 1]! : ''
}

/**
 * Find or recreate the settingsDir for a previous conversation.
 *
 * The slug in ~/.claude/projects/ is computed from settingsDir via
 * path.resolve(settingsDir).replace(/[^a-zA-Z0-9]/g, '-').
 *
 * Strategy:
 * 1. Find slug dir containing <conversationId>.jsonl
 * 2. Try to find existing settingsDir in SESSIONS_BASE matching that slug
 * 3. If not found (e.g. /tmp cleared after container restart), reverse-
 *    compute the settingsDir path from the slug and recreate the dir.
 */
export function findOrRecreateSettingsDir(conversationId: string, _tokenId: string): string | null {
  const projectsDir = path.join(os.homedir(), '.claude', 'projects')
  const jsonlFilename = `${conversationId}.jsonl`

  try {
    if (!fs.existsSync(projectsDir)) return null
    const slugDirs = fs.readdirSync(projectsDir, { withFileTypes: true })
    for (const slugDir of slugDirs) {
      if (!slugDir.isDirectory()) continue
      const jsonlPath = path.join(projectsDir, slugDir.name, jsonlFilename)
      if (!fs.existsSync(jsonlPath)) continue

      // Repair before CLI reads it — without this CLI will pick a
      // synthetic <synthetic> UUID as previous_message_id → 400 forever,
      // or choke on a torn line / broken parentUuid chain left by a
      // mid-write kill (network drop → instant reconnect).
      try { repairJsonl(jsonlPath) } catch (e) {
        warnLog('repairJsonl failed', { jsonlPath, error: String(e) })
      }

      const slug = slugDir.name
      const existing = scanForSettingsDirBySlug(slug)
      if (existing) return existing

      // Not found — reverse the slug back to a path and recreate.
      // Slug format: -tmp-claude-bridge-sessions-TOKENID-CWD-SESSIONUUID
      // Original path: /tmp/claude-bridge-sessions/TOKENID-CWD/SESSIONUUID
      const reconstructed = reverseSlugToPath(slug)
      if (reconstructed) {
        fs.mkdirSync(reconstructed, { recursive: true })
        debugLog('Resume: recreated settingsDir from slug', { slug, path: reconstructed })
        return reconstructed
      }
    }
  } catch { /* ignore */ }
  return null
}

/** Scan SESSIONS_BASE for a directory matching the given slug. */
export function scanForSettingsDirBySlug(slug: string): string | null {
  try {
    if (!fs.existsSync(SESSIONS_BASE)) return null
    const tokenDirs = fs.readdirSync(SESSIONS_BASE, { withFileTypes: true })
    for (const tokenDir of tokenDirs) {
      if (!tokenDir.isDirectory()) continue
      const tokenPath = path.join(SESSIONS_BASE, tokenDir.name)
      const sessionDirs = fs.readdirSync(tokenPath, { withFileTypes: true })
      for (const sessionDir of sessionDirs) {
        if (!sessionDir.isDirectory()) continue
        const candidate = path.join(tokenPath, sessionDir.name)
        const candidateSlug = path.resolve(candidate).replace(/[^a-zA-Z0-9]/g, '-')
        if (candidateSlug === slug) return candidate
      }
    }
  } catch { /* ignore */ }
  return null
}

/**
 * Reverse a slug back to a filesystem path. Slug is generated by
 * path.resolve(dir).replace(/[^a-zA-Z0-9]/g, '-') so we can't perfectly
 * reverse, but we know the prefix is SESSIONS_BASE and the trailing
 * 36-char block is a UUID (preserved literally — its hyphens survive the
 * slugify pass since they were already hyphens).
 *
 * After the base prefix the structure is TOKEN_DIR/SESSION_UUID. The
 * TOKEN_DIR is sanitized via sanitizeDirName which uses underscores, so
 * we restore -→_ for that segment.
 */
export function reverseSlugToPath(slug: string): string | null {
  const basePath = path.resolve(SESSIONS_BASE)
  const baseSlug = basePath.replace(/[^a-zA-Z0-9]/g, '-')
  if (!slug.startsWith(baseSlug + '-')) return null

  const remainder = slug.slice(baseSlug.length + 1)
  const uuidMatch = remainder.match(/^(.+)-([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})$/)
  if (!uuidMatch) {
    // No UUID found — treat entire remainder as token dir name
    return path.join(SESSIONS_BASE, remainder)
  }
  const tokenDirSlug = uuidMatch[1]!
  const sessionUuid = uuidMatch[2]!
  const tokenDirName = tokenDirSlug.replace(/-/g, '_')
  return path.join(SESSIONS_BASE, tokenDirName, sessionUuid)
}

// ---------------------------------------------------------------------------
// JSONL repair on resume
// ---------------------------------------------------------------------------

export interface JsonlRepairStats {
  repaired: boolean
  droppedUnparseable: number
  droppedSynthetic: number
  relinkedParents: number
  truncatedTail: number
}

const NO_REPAIR: JsonlRepairStats = {
  repaired: false, droppedUnparseable: 0, droppedSynthetic: 0, relinkedParents: 0, truncatedTail: 0,
}

/**
 * Repair a Claude CLI conversation JSONL before --resume.
 *
 * Corruption sources observed in production:
 *  - A mid-write kill (WS drop used to hard-kill the PTY; instant reconnect
 *    spawned a second writer) leaves a torn (unparseable) trailing line
 *    and/or entries whose parentUuid points at a uuid that never got
 *    persisted.
 *  - When a streaming response is cut off mid-flight (network drop, 90s
 *    watchdog, corp-proxy RST), CLI persists the partial `assistant` entry
 *    with `stop_reason: null`, then keeps writing local "synthetic"
 *    placeholders (`model: "<synthetic>"`) with **UUID** ids that don't
 *    start with `msg_`. On the next request CLI grabs the latest assistant
 *    `message.id` for `diagnostics.previous_message_id` and Anthropic 400s
 *    (`must be the id from a prior /v1/messages response`) — the session is
 *    then permanently stuck in a retry loop.
 *
 * Repair passes (all in one read → one atomic write):
 *  1. Drop unparseable lines (torn writes).
 *  2. Drop entries whose message.id is set but is not a real `msg_*` id
 *     (the CLI's synthetic error placeholders).
 *  3. Relink parentUuid: any entry pointing at a uuid that no longer exists
 *     (dropped above, or never persisted) is re-parented to the nearest
 *     preceding kept entry — restores chain connectivity so CLI can walk it.
 *  4. Tail truncation: if a broken assistant remains after the last real
 *     completed assistant turn (msg_ id + stop_reason set), cut there — the
 *     follow-up request then uses a real msg_id as previous_message_id.
 *
 * Always backs up the original as `<name>.bak-<ts>` before writing; the
 * write itself is tmp-file + rename so a crash mid-repair can't tear the
 * transcript again.
 */
export function repairJsonl(jsonlPath: string): JsonlRepairStats {
  let content: string
  try { content = fs.readFileSync(jsonlPath, 'utf8') }
  catch { return NO_REPAIR }

  const rawLines = content.split('\n').filter(l => l.trim().length > 0)
  if (rawLines.length === 0) return NO_REPAIR

  // Pass 1+2: parse, drop torn lines and synthetic-id entries.
  type Parsed = { obj: Record<string, unknown>; line: string }
  const kept: Parsed[] = []
  let droppedUnparseable = 0
  let droppedSynthetic = 0
  for (const line of rawLines) {
    let obj: Record<string, unknown>
    try { obj = JSON.parse(line) }
    catch { droppedUnparseable++; continue }
    const mid = (obj as { message?: { id?: unknown } }).message?.id
    if (typeof mid === 'string' && mid.length > 0 && !mid.startsWith('msg_') && !isCompactCheckpoint(line)) {
      droppedSynthetic++
      continue
    }
    kept.push({ obj, line })
  }
  if (kept.length === 0) return NO_REPAIR

  // Pass 3: relink parentUuid to the nearest preceding kept entry.
  const uuids = new Set<string>()
  let relinkedParents = 0
  let lastUuid: string | null = null
  for (const p of kept) {
    const o = p.obj as { uuid?: unknown; parentUuid?: unknown }
    if (typeof o.parentUuid === 'string' && o.parentUuid && !uuids.has(o.parentUuid)) {
      o.parentUuid = lastUuid
      relinkedParents++
      p.line = JSON.stringify(p.obj)
    }
    if (typeof o.uuid === 'string' && o.uuid) {
      uuids.add(o.uuid)
      lastUuid = o.uuid
    }
  }

  // Pass 4: tail truncation of a genuinely-torn last turn only. The "last good"
  // anchor is the last COMPLETED assistant OR a compaction checkpoint — so an
  // interrupted stream that lands right after a compact_boundary can no longer
  // drag the whole compacted segment (+ everything after it) into the bin. Only
  // the broken trailing entries past that checkpoint are removed.
  let lastGoodIdx = -1
  for (let i = kept.length - 1; i >= 0; i--) {
    if (isCompletedRealAssistant(kept[i]!.line) || isCompactCheckpoint(kept[i]!.line)) { lastGoodIdx = i; break }
  }
  let truncatedTail = 0
  let final = kept
  if (lastGoodIdx >= 0) {
    let hasBadTail = false
    for (let i = lastGoodIdx + 1; i < kept.length; i++) {
      if (isBrokenAssistant(kept[i]!.line)) { hasBadTail = true; break }
    }
    if (hasBadTail) {
      // Drop everything after the last good assistant entry. We deliberately
      // also drop trailing user/meta entries — CLI rebuilds those on resume,
      // and orphan references to the dropped tail would break the chain.
      truncatedTail = kept.length - lastGoodIdx - 1
      final = kept.slice(0, lastGoodIdx + 1)
    }
  }

  const changed = droppedUnparseable > 0 || droppedSynthetic > 0 || relinkedParents > 0 || truncatedTail > 0
  if (!changed) return NO_REPAIR

  try { fs.copyFileSync(jsonlPath, `${jsonlPath}.bak-${Date.now()}`) }
  catch (e) {
    warnLog('repairJsonl backup failed; skipping repair to avoid data loss', {
      jsonlPath, error: String(e),
    })
    return NO_REPAIR
  }
  const tmpPath = `${jsonlPath}.repair-tmp`
  fs.writeFileSync(tmpPath, final.map(p => p.line).join('\n') + '\n')
  fs.renameSync(tmpPath, jsonlPath)

  const stats: JsonlRepairStats = {
    repaired: true, droppedUnparseable, droppedSynthetic, relinkedParents, truncatedTail,
  }
  debugLog('repairJsonl: transcript repaired', { jsonlPath, ...stats })
  return stats
}

/**
 * Repair the transcript for a session that resumes via reuseSettingsDir
 * (model/effort restart). The projects/ slug is derived from the settingsDir
 * the same way CLI derives it, so we can locate the JSONL without scanning.
 */
export function repairTranscriptForResume(settingsDir: string, conversationId: string): JsonlRepairStats {
  const slug = path.resolve(settingsDir).replace(/[^a-zA-Z0-9]/g, '-')
  const jsonlPath = path.join(os.homedir(), '.claude', 'projects', slug, `${conversationId}.jsonl`)
  if (!fs.existsSync(jsonlPath)) return NO_REPAIR
  try { return repairJsonl(jsonlPath) }
  catch (e) {
    warnLog('repairTranscriptForResume failed', { jsonlPath, error: String(e) })
    return NO_REPAIR
  }
}

/** True iff the JSONL line is an assistant entry that came from a real
 *  /v1/messages response that completed successfully. */
function isCompletedRealAssistant(line: string): boolean {
  if (!line || !line.trim()) return false
  let entry: { type?: string; message?: { id?: unknown; model?: unknown; stop_reason?: unknown } }
  try { entry = JSON.parse(line) }
  catch { return false }
  if (entry.type !== 'assistant') return false
  const m = entry.message
  if (!m) return false
  if (typeof m.id !== 'string' || !m.id.startsWith('msg_')) return false
  if (m.model === '<synthetic>') return false
  // stop_reason: null means the stream was interrupted before message_stop;
  // Anthropic doesn't recognise the msg_id as a completed response.
  if (m.stop_reason === null || m.stop_reason === undefined) return false
  return true
}

/** True iff the line is an assistant entry that would break the
 *  previous_message_id chain on the next CLI request. */
/** A CLI-written compaction checkpoint: the `compact_boundary` system marker or
 *  its summary. These are LEGITIMATE, resumable state — the repair must never
 *  treat them as corruption or truncate across them, or it silently destroys a
 *  whole compacted segment (+ everything after) that the user still needs.
 *
 *  Detects EVERY on-disk shape the rest of the codebase recognises, because a
 *  miss here re-opens the exact data-loss bug: the `compact_boundary` system
 *  entry, the `type:"compact-summary"` variant, the `isCompactSummary` flag,
 *  and — since some CLI versions omit the flag — the literal summary marker text
 *  the renderer also keys on. */
function isCompactCheckpoint(line: string): boolean {
  if (!line || !line.trim()) return false
  let e: { type?: string; subtype?: string; isCompactSummary?: unknown; message?: { content?: unknown } } | null
  try { e = JSON.parse(line) }
  catch { return false }
  if (!e || typeof e !== 'object') return false
  if (e.type === 'system' && e.subtype === 'compact_boundary') return true
  if (e.type === 'compact-summary') return true
  if (e.isCompactSummary === true) return true
  const c = e.message?.content
  const text = typeof c === 'string' ? c
    : Array.isArray(c) ? c.map((b) => (b as { text?: string }).text ?? '').join(' ') : ''
  return /compacted\s*\(ctrl[+\s]*o/i.test(text)
}

function isBrokenAssistant(line: string): boolean {
  if (!line || !line.trim()) return false
  let entry: { type?: string; message?: { id?: unknown; model?: unknown; stop_reason?: unknown } }
  try { entry = JSON.parse(line) }
  catch { return false }
  if (entry.type !== 'assistant') return false
  const m = entry.message
  if (!m) return false
  if (m.model === '<synthetic>') return true
  if (typeof m.id !== 'string' || !m.id.startsWith('msg_')) return true
  if (m.stop_reason === null) return true
  return false
}
