// ============================================================================
// Thin barrel — types were moved to src/core/types/
// Kept here for backwards compatibility with existing imports.
// ============================================================================

export type {
  SessionState,
  McpLogEntry,
  PtySession,
  ToolDefinition,
  SessionConfig,
  TreeNode,
  SavedSession,
  SyncUserData,
  SyncProjectData,
  McpToolRequest,
  McpToolResponse,
  McpToolDenied,
  PendingMcpCall,
  PendingElicitation,
  ElicitationResult,
  WsMsgSessionCreate,
  WsMsgSessionInput,
  WsMsgSessionSubmitText,
  WsMsgSessionResize,
  WsMsgMcpResponse,
  WsMsgMcpDenied,
  WsMsgElicitationResponse,
  WsMsgSessionResume,
  WsMsgSessionChangeEffort,
  WsMsgSessionChangeModel,
  WsMsgSessionDeleteData,
  WsMsgRegisterExternalTools,
  WsMsgJsonlDownloadRequest,
  WsMsgJsonlSyncRequest,
  ElectronToServerMsg,
  WsMsgSessionCreated,
  WsMsgSessionOutput,
  WsMsgSessionExit,
  WsMsgSessionError,
  WsMsgMcpCall,
  WsMsgJsonlEntries,
  WsMsgJsonlStatus,
  WsMsgElicitationRequest,
  WsMsgAgentSpawned,
  WsMsgTreeUpdate,
  WsMsgSessionRestarted,
  WsMsgSessionActivity,
  WsMsgJsonlDownloadResponse,
  ServerToElectronMsg,
} from '../types'
